name: "NowSecure SBOM"

on:
  workflow_dispatch:
    branches: [ master ]
    
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build App 
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: DVIA-v2/DVIA-v2.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MY_MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: DVIA-v2/DVIA-v2.xcworkspace # optional
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          configuration: "Release"
          export-method: "ad-hoc"
          
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /Users/runner/work/DVIA-v2/DVIA-v2/output.ipa
          retention-days: 3  
          
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NowSecure Mobile SBOM
        uses: nowsecure/nowsecure-sbom-action@v2
        timeout-minutes: 120
        with:
          platform_token: ${{ secrets.NS_TOKEN }}
          # TODO: Replace app file with .apk or .ipa.
          app_file: output.ipa
          # TODO: Replace the Group ID.
          group_id: "602abed9-4c66-453d-8431-da0195b682de"
          
